### ISSUE TITLE
Export is broken

### ISSUE THREAD

**Issue by neosquid** [Duefectu/ZXGraphics#2]
Hi, trying out the tool tonight in VSCode, it's great, but I think export option is broken 

Runtime Status for the Extension in VSCODE reports ~ "Cannot read properties of undefined (reading 'with')"

**Comment by Duefectu** [comment]
Hi @neosquid, sorry for the delay in the response!
What operating system are you using, Windows, Linux or Mac?
Can you send me the file you have the problem with to duefectucorp@gmail.com to see if I can reproduce the error?

Thanks for your report!

**Comment by neosquid** [comment]
Is there a set save location for the exported .asm file? Maybe I'm not looking in the correct location. I've tried on MacOS and Windows, the extension seems to give no feedback if the file is created or not. I sent the graphics .fnt file I've been working on. Thanks.

**Comment by Duefectu** [comment]
It saves on the root folder.
Anyway, I'm working on a new export system with more options, I'll see if I can add something about the destination folder.

**Comment by neosquid** [comment]
Ok, I had another look in my root folder, and there's no exported file after saving.

**Comment by Duefectu** [comment]
Hello,

I've opened your file and exported it to all formats without any problem, so I guess it's a permissions issue. It would help me to narrow down the problem a bit. Can you answer these questions?:

1. What operating system do you use (Windows, Linux or Mac)?
2. Do you open the file on its own, or within a project?
3. Do you open the folder or a VSCoode workspace?

Exports are done in the main project folder, so ideally you should open a folder or better a workspace, which ensures that access permissions are appropriate.

**Comment by neosquid** [comment]
Thanks, I've never used workspace before ~ the file was created! 

Thanks for the support.
